spring:
  main:
    banner-mode: off
  r2dbc:
    url: r2dbc:h2:mem:///pineapple?options=DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username:
    password:

logging:
  level:
    org.springframework.data.r2dbc: DEBUG
